global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orders-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']

rule_files:
  - /etc/prometheus/alerting/alerts.yml
